# Generated by Django 4.1.7 on 2023-04-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rating', models.FloatField(default=0)),
                ('last_accept', models.DateTimeField(null=True)),
            ],
        ),
    ]
