# Generated by Django 4.1.7 on 2023-04-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='inn',
            field=models.IntegerField(default=12345678),
        ),
    ]
