# Generated by Django 4.1.7 on 2023-04-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_member_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(default='Санкт-Петербург, ул. Пионерская, д. 26', max_length=50),
        ),
    ]
