# Generated by Django 4.1.7 on 2023-04-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_section_orders_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
